core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_view
from django.urls import include, path

from users import views as user_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackoverflow.urls')),

    # Authentication System
    path('register/', user_view.register, name="register"),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name='logout'),

    # Profile system
    path('profile/', user_view.profile, name="profile"),
    path('profile/update/', user_view.profile_update, name="profile_update")
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackoverflow/urls.py
from django.urls import path

from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),

    path('like/<int:pk>/', views.like_view, name='like_post'),

    path('questions/', views.QuestionListView.as_view(), name='question-lists'),
    path('questions/new/', views.QuestionCreateView.as_view(), name='question-create'),
    path('questions/<int:pk>/', views.QuestionDetailView.as_view(), name='question-detail'),
    path('questions/<int:pk>/update/', views.QuestionUpdateView.as_view(), name='question-update'),
    path('questions/<int:pk>/delete/', views.QuestionDeleteView.as_view(), name='question-delete'),
    path('questions/<int:pk>/comment/', views.AddCommentView.as_view(), name='question-comment'),

]

users/urls.py
from django.urls import path

from . import views

urlpatterns = [

]

users/models.py
from django.contrib.auth.models import User
from django.db import models
from PIL import Image


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.CharField(max_length=255)
    phone = models.IntegerField(null=True, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pic')

    def __str__(self):
        return f'{self.user.username} - Profile'
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.contrib.auth.models import User

from .models import Profile


class UserRegistrationForm(UserCreationForm):
    email = models.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'phone', 'image']

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import ProfileUpdateForm, UserRegistrationForm, UserUpdateForm


# Create your views here.
def register(request):
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            form.save()
            messages.success(request, f'Account Successfully Created. You can Login!')
            return redirect('login')

    else:
        form = UserRegistrationForm()

    return render(request, 'register.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'profile.html')


@login_required()
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Account Updated Successfully')
            return redirect('profile')

        else:
            u_form = UserUpdateForm(request.POST, instance=request.user)
            p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        context = {
            'u_form': u_form,
            'p_form': p_form
        }

        return render(request, 'profile_update.html', context)

users/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Stack Overflow - Where Developers Learn, Share, &amp; Build Careers</title>
    <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196">
    <link rel="apple-touch-icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="image_src" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body>

<header>

<div class="nav-container">
    <nav>
        <div class="nav-brand">
            <div class="hamburger-menu-container">

                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <div class="nav-dropdown-menu">
                    <a href="#" class="current-link">Home</a>
                    <h5>Public</h5>
                    <ul class="nav-ul">
                        <li class="nav-item">
                            <i class="fas fa-globe-europe"></i>
                            <a href="" class="nav-link">Stack Overflow</a>
                        </li>
                        <li class="nav-item"><a href="#" class="nav-link">Tags</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Users</a></li>
                    </ul>
                    <h5>Find a Job</h5>
                    <ul class="nav-ul">
                        <li class="nav-item"><a href="#" class="nav-link">Jobs</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Companies</a></li>
                    </ul>
                    <h5>Teams <a href="#" >What's this ?</a></h5>
                    <a href="#" class="nav-link">
                        <i class="fas fa-briefcase"></i>
                        <span>Free 30 Day Trial</span>
                    </a>
                </div>
            </div>

            <a href="" class="nav-icon">
                <i class="fab fa-stack-overflow"></i>
                <a href="{% url 'stackbase:home' %}" style="text-decoration: none; color: black;">
                    <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span></a>
                <!-- <div class="nav-icon-text">stack <span class="nav-bold-text">overflow</span> -->
            </a>
        </div>
</div>

</div>
        <div class="nav-base-links">
            <ul>
                <li><a href="#">About</a></li>
                <li><a href="#">Products</a></li>
                <li><a href="#">For Teams</a></li>
            </ul>
        </div>
        <div class="nav-search">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="" name="search-area" placeholder="Search...">
                    <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>
            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span>  search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
            {% if user.is_authenticated %}
                <a href="{% url 'login' %}" class="btn btn-login">Profile</a>
                <a href="{% url 'logout' %}" class="btn btn-register">Logout</a>
            {% else %}
                <a href="{% url 'login' %}" class="btn btn-login">Log in</a>
                <a href="{% url 'register' %}" class="btn btn-register">Sign up</a>
            {% endif %}
        </div>
    </nav>
</div>
<!-- <h1 style="font-size: 20px;">hello</h1> -->
    <div style="margin-top: 10px;">
        {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <h4 style="text-align: center;">{{ message }}</h4>
      </div>
      {% endfor %}
    {% endif %}
    </div>


</header>

<!-- Add block content here -->
<!-- Add enbdblock content here -->

{% block content %}

{% endblock content %}

<section class="jobs">
    <div class="container">

        <div class="jobs-content">
            <h3 class="jobs-title">Looking for a job?</h3>
            <div class="jobs-body">
                    <div class="jobs-items">
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-tech.svg?v=42f011c01763" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by technology</p>
                            </div>
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-salary.svg?v=401840ff8931" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by salary</p>
                            </div>
                        </div>
                        <div class="column">
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-visa.svg?v=1f3acc6dc772" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse jobs by visa sponsorship</p>
                            </div>
                            <div class="jobs-item">
                                <img src="https://cdn.sstatic.net/Img/home/jobs-remote.svg?v=a4b4d1b5a80c" alt="" class="jobs-item-img">
                                <p class="jobs-item-description">Browse remote-friendly jobs</p>
                            </div>
                        </div>
                    </div>
                    <div class="jobs-btn">
                        <div class="btn btn-orange jobs-btn">View all jobs</div>
                    </div>
            </div>
        </div>
    </div>
</section>

<footer class="footer">
    <img src="https://cdn.sstatic.net/Img/home/robot.svg?v=dfa16a330cbd" alt="" class="footer-robot-img">
<div class="container">
    <div class="footer-content">
        <div class="footer-icon">
            <i class="fab fa-stack-overflow"></i>
        </div>
        <div class="footer-nav">
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">Stack Overflow</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item"><a href="#" class="footer-link">Questions</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Jobs</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Developer Jobs Directory</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Salary Calculator</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Help</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Mobile</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Disable Responsiveness</a></li>
                </ul>
            </div>
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">Products</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item"><a href="#" class="footer-link">Teams</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Talent</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Advertising</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Enterprise</a></li>
                </ul>
            </div>
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">Company</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item"><a href="#" class="footer-link">About</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Press</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Work Here</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Legal</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Privacy Policy</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Contact Us</a></li>
                </ul>
            </div>
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">Stack Exchange Network</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Technology</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Life / Arts</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div></li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Culture / Recreation</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Science</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Other</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
        <div class="footer-another-links">
            <div class="social-media">
                <ul>
                    <li>
                        <a href="#">Blog</a>
                    </li>
                    <li>
                        <a href="#">Facebook</a>
                    </li>
                    <li>
                        <a href="#">Twitter</a>
                    </li>
                    <li>
                        <a href="#">LinkedIn</a>
                    </li>
                    <li>
                        <a href="#">Instagram</a>
                    </li>
                </ul>
            </div>
            <div class="copyright">
                <p>site design / logo © 2020 Stack Exchange Inc; user contributions licensed under <a href="https://stackoverflow.com/help/licensing">cc by-sa</a>. rev 2020.10.2.37725</p>
            </div>
        </div>
    </div>

</div>
</footer>

<!-- <script src="assets/js/main.js"></script> -->
<script src="{% static 'main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

users/templates/login.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        @import url('https://fonts.googleapis.com/css?family=Poppins');

/* BASIC */

html {
  background-color: #e7e7e7;
  background: linear-gradient(200deg, yellow 0%, rgb(236, 146, 0) 100%);
}

body {
  font-family: "Poppins", sans-serif;
  height: 100vh;
}

a {
  color: #92badd;
  display:inline-block;
  text-decoration: none;
  font-weight: 400;
}

h2 {
  text-align: center;
  font-size: 16px;
  font-weight: 600;
  text-transform: uppercase;
  display:inline-block;
  margin: 40px 8px 10px 8px; 
  color: #cccccc;
}



/* STRUCTURE */

.wrapper {
  display: flex;
  align-items: center;
  flex-direction: column; 
  justify-content: center;
  width: 100%;
  min-height: 100%;
  padding: 20px;
}

#formContent {
  -webkit-border-radius: 10px 10px 10px 10px;
  border-radius: 10px 10px 10px 10px;
  background: #fff;
  padding: 30px;
  width: 90%;
  max-width: 450px;
  position: relative;
  padding: 0px;
  -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
  text-align: center;
}

#formFooter {
  background-color: #f6f6f6;
  border-top: 1px solid #dce8f1;
  padding: 25px;
  text-align: center;
  -webkit-border-radius: 0 0 10px 10px;
  border-radius: 0 0 10px 10px;
}

/* TABS */

h2.inactive {
  color: #cccccc;
}

h2.active {
  color: #0d0d0d;
  border-bottom: 2px solid #5fbae9;
}

/* FORM TYPOGRAPHY*/

input[type=button], input[type=submit], input[type=reset]  {
  background-color: #56baed;
  border: none;
  color: white;
  padding: 15px 80px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  text-transform: uppercase;
  font-size: 13px;
  -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
  margin: 5px 20px 40px 20px;
  -webkit-transition: all 0.3s ease-in-out;
  -moz-transition: all 0.3s ease-in-out;
  -ms-transition: all 0.3s ease-in-out;
  -o-transition: all 0.3s ease-in-out;
  transition: all 0.3s ease-in-out;
}

input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
  background-color: #39ace7;
}

input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
  -moz-transform: scale(0.95);
  -webkit-transform: scale(0.95);
  -o-transform: scale(0.95);
  -ms-transform: scale(0.95);
  transform: scale(0.95);
}

input[type=text] {
  background-color: #f6f6f6;
  border: none;
  color: #0d0d0d;
  padding: 10px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 5px;
  width: 85%;
  border: 2px solid #f6f6f6;
  -webkit-transition: all 0.5s ease-in-out;
  -moz-transition: all 0.5s ease-in-out;
  -ms-transition: all 0.5s ease-in-out;
  -o-transition: all 0.5s ease-in-out;
  transition: all 0.5s ease-in-out;
  -webkit-border-radius: 5px 5px 5px 5px;
  border-radius: 5px 5px 5px 5px;
}

input[type=text]:focus {
  background-color: #fff;
  border-bottom: 2px solid #5fbae9;
}

input[type=text]:placeholder {
  color: #cccccc;
}

/* ANIMATIONS */

/* Simple CSS3 Fade-in-down Animation */
.fadeInDown {
  -webkit-animation-name: fadeInDown;
  animation-name: fadeInDown;
  -webkit-animation-duration: 1s;
  animation-duration: 1s;
  -webkit-animation-fill-mode: both;
  animation-fill-mode: both;
}

@-webkit-keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

@keyframes fadeInDown {
  0% {
    opacity: 0;
    -webkit-transform: translate3d(0, -100%, 0);
    transform: translate3d(0, -100%, 0);
  }
  100% {
    opacity: 1;
    -webkit-transform: none;
    transform: none;
  }
}

/* Simple CSS3 Fade-in Animation */
@-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
@keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

.fadeIn {
  opacity:0;
  -webkit-animation:fadeIn ease-in 1;
  -moz-animation:fadeIn ease-in 1;
  animation:fadeIn ease-in 1;

  -webkit-animation-fill-mode:forwards;
  -moz-animation-fill-mode:forwards;
  animation-fill-mode:forwards;

  -webkit-animation-duration:1s;
  -moz-animation-duration:1s;
  animation-duration:1s;
}

.fadeIn.first {
  -webkit-animation-delay: 0.4s;
  -moz-animation-delay: 0.4s;
  animation-delay: 0.4s;
}

.fadeIn.second {
  -webkit-animation-delay: 0.6s;
  -moz-animation-delay: 0.6s;
  animation-delay: 0.6s;
}

.fadeIn.third {
  -webkit-animation-delay: 0.8s;
  -moz-animation-delay: 0.8s;
  animation-delay: 0.8s;
}

.fadeIn.fourth {
  -webkit-animation-delay: 1s;
  -moz-animation-delay: 1s;
  animation-delay: 1s;
}

/* Simple CSS3 Fade-in Animation */
.underlineHover:after {
  display: block;
  left: 0;
  bottom: -10px;
  width: 0;
  height: 2px;
  background-color: #56baed;
  content: "";
  transition: width 0.2s;
}

.underlineHover:hover {
  color: #0d0d0d;
}

.underlineHover:hover:after{
  width: 100%;
}

/* OTHERS */

*:focus {
    outline: none;
} 

#icon {
  width:60%;
}
a{
  text-decoration: none;
}
* {
  box-sizing: border-box;
}
    </style>
</head>
<body>
    <div class="wrapper fadeInDown">
        <div id="formContent">
          <!-- Tabs Titles -->
          <h2 class="active"><a href="" style="text-decoration: none;">Sign In</a> </h2>
          <h2 class="inactive underlineHover"> <a href="" style="text-decoration: none;">Sign Up</a> </h2>

      
          <!-- Icon -->
          <div class="fadeIn first">
          </div>
      
          <!-- Login Form -->
          <!-- <form method="POST">
                {% csrf_token %}
                <div class="container" p> -->
                  <!-- {{form|crispy}} -->
                  <!-- <input type="submit" class="fadeIn fourth" value="Sign In"> -->
          <!-- </form> -->

          <form action="" method="POST">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" class="fadeIn fourth" value="Sign In">

          </form>
    
          <!-- Remind Password -->
          <div id="formFooter">
            <p>Don't have an account yet? <a class="underlineHover" href="{% url 'register' %}">Register </a></p>
          </div>
      
        </div>
      </div>
</body>
</html>
{% endblock content %}

users/templates/logout.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <title>Logout Page</title>
        <style>
            body{
                background: linear-gradient(230deg, orange 0%, yellow 100%);

            }
            .containerr{
                margin-top: 100px;
                margin-bottom: 130px;

            }
            #logoutid1{
                text-align: center;
                font-size: 30px;
                color: rgb(0, 0, 0);
                font-weight: 600;
                font-family: 'Poppins', sans-serif;
            }
            #logout-btn{
                text-align: center;
                margin: auto;
                display: flex;
                justify-self: center;
            }
            #fa{
                color: white;
                text-decoration: none;
            }
        </style>
    </head>
    <body>
        <div class="containerr">
            <h3 id="logoutid1">You have been logged out!!</h3>
            <div>
                <button class="btn btn-primary" id="logout-btn"><a id="fa" href="{% url 'login' %}">LOGIN</a></button>

            </div>
        </div>
    </body>
    </html>
    {% endblock content %}